version: '3.8'

services:
  # 1. App (Nuxt 4)
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    container_name: ceoris-nuxt
    ports:
      - "12001:3000"
    environment:
      - NUXT_API_BASE=http://server:12000 # Comunicação interna do Nitro via SSR
      - NUXT_PUBLIC_API_BASE=http://localhost:12000 # Comunicação externa via Browser
      - CHOKIDAR_USEPOLLING=true # Hot reload
    volumes:
      - ./app:/app
      - /app/node_modules
      - /app/.nuxt
    networks:
      - ceoris_net
    depends_on:
      - server

  # 2. Server (Go Fiber)
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: ceoris-goserver
    ports:
      - "12000:12000"
    environment:
      - ENV=development
      - PORT=12000
      - TIMEZONE=America/Sao_Paulo
      - POCKETBASE_URL=http://database:8090 # Comunicação interna com o banco
    volumes:
      - ./data/notebooks:/root/data/notebooks
    networks:
      - ceoris_net
    depends_on:
      - database
    env_file:
      - .env

  # 3. Banco de Dados (PocketBase Customizado)
  database:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: ceoris-pocketbase
    ports:
      - "12090:8090" # Portal de Admin acessível em http://localhost:12090/_/
    volumes:
      - ./db/pb_data:/root/pb_data
      - ./db/pb_migrations:/root/pb_migrations # Aqui vai a nossa magia
    networks:
      - ceoris_net
    command: ["./main", "serve", "--http=0.0.0.0:8090"]
    env_file:
      - .env

networks:
  ceoris_net:
    driver: bridge
