version: '3.8'

services:
  # ==========================================
  # BACKEND: Go Server + PocketBase Embedded
  # ==========================================
  api:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: ceoris-api
    restart: unless-stopped
    ports:
      - "12000:12000" # API Rest (Fiber)
      - "8090:8090"   # Admin UI do PocketBase
    volumes:
      - ./db:/app/db
      - ./pb_data:/app/pb_data
      - ./pb_migrations:/app/pb_migrations
      # Pasta onde os Cadernos (.md) e anexos serão salvos no formato Flat-file
      - ./data/notebooks:/app/data/notebooks
    env_file:
      - .env
    environment:
      - ENV=development
      - PORT=12000
      - TIMEZONE=America/Sao_Paulo

  # ==========================================
  # FRONTEND: Nuxt 4 App (Admin & Cadernos)
  # ==========================================
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: ceoris-web
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      # Sincronização local para dev caso não use o container pra rodar o pnpm dev
      - ./app:/app
      - /app/node_modules
    environment:
      # Diz ao Nuxt onde a API do Go está
      - NUXT_PUBLIC_API_BASE=http://api:12000
    depends_on:
      - api
